name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Usar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install --include=dev

      - name: Arreglar permisos de jest
        run: chmod +x node_modules/.bin/jest

      - name: Verificar versión de jest
        run: npx jest --version

      - name: Ejecutar pruebas con cobertura
        run: npm run test:coverage
