name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Usar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Build (opcional si generas HTML dinámico)
        run: echo "build step (si aplica)"

      - name: Desplegar a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
